/*const fetchData = async () => {
    try {
      const result = await Test();

      console.log(result)
    } catch (error) {
      console.error("Erreur lors de la récupération des données :", error);
    }
  };

  fetchData();

  const fetchData2 = async () => {
      try {
        const result = await Test2();

        console.log(result)
      } catch (error) {
        console.error("Erreur lors de la récupération des données :", error);
      }
    };

    fetchData2();*/

    /*if (MockedDataUser && MockedDataUser != null) {
            const result = MockedDataUser.USER_MAIN_DATA
            console.log("Voici les données mockés : ", result)
        } else {
            const result = await Services.getFirstUser()
            console.log( result)
        }*/